name: MSC ETA Tracking Automation

on:

  workflow_dispatch:

  schedule:

    - cron: '0 6 * * *' # Her gün saat 09:00'da (UTC 06:00 Türkiye 09:00)

jobs:

  run-script:

    runs-on: ubuntu-latest

    steps:

      - name: Reposoyu klonla

        uses: actions/checkout@v3

      - name: Python ortamını kur

        uses: actions/setup-python@v4

        with:

          python-version: '3.10'

      - name: Bağımlılıkları yükle

        run: |

          sudo apt-get update

          sudo apt-get install -y libglib2.0-0 libnss3 libatk-bridge2.0-0 libcups2 libxss1 libasound2 libgbm-dev libgtk-3-0

          python -m pip install --upgrade pip

          pip install pandas google-api-python-client google-auth google-auth-oauthlib google-auth-httplib2 playwright

          playwright install chromium

      - name: Scripti çalıştır

        run: python src/main.py

        env:

          GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }}

          SPREADSHEET_ID: ${{ secrets.SPREADSHEET_ID }}
 
